"""
models.py
=========
Pydantic data models for the exam parser.

This file defines the EXACT shape of the data that Member 3 produces
and hands off to Members 4, 5, and 6.

Why Pydantic?
    - It validates data types automatically
      (e.g. marks must be int or None, not a string)
    - It generates clean JSON output with model.model_dump()
    - It makes the contract explicit and enforced in code
    - It gives clear error messages when the wrong type is passed

Models defined here:
    1. Question       — a single exam question record
    2. ParsedDocument — the full result of parsing one PDF
    3. Topic          — a topic from the official syllabus

The agreed Question contract (from the project spec):
╔══════════════════╦══════════════╦═══════════════════════════════════════╗
║ Field            ║ Filled by    ║ Notes                                 ║
╠══════════════════╬══════════════╬═══════════════════════════════════════╣
║ question_id      ║ Member 3     ║ auto-generated UUID or DB serial      ║
║ document_id      ║ Member 6     ║ provided as input to parse()          ║
║ page             ║ Member 3     ║ 1-indexed                             ║
║ raw_text         ║ Member 3     ║ exactly as extracted                  ║
║ cleaned_text     ║ Member 4     ║ NULL initially                        ║
║ year             ║ Member 3     ║ from document, propagated             ║
║ exam_type        ║ Member 3     ║ e.g. "End Semester"                   ║
║ section          ║ Member 3     ║ e.g. "A", "B"                         ║
║ marks            ║ Member 3     ║ extracted from text, or NULL          ║
║ is_compulsory    ║ Member 3     ║ True/False/None                       ║
║ topic_id         ║ Member 4     ║ NULL initially                        ║
║ repeat_group_id  ║ Member 4     ║ NULL initially                        ║
╚══════════════════╩══════════════╩═══════════════════════════════════════╝
"""

import uuid
from typing import Optional
from pydantic import BaseModel, Field, field_validator, model_validator


# ═══════════════════════════════════════════════════════════════════
# QUESTION MODEL
# ═══════════════════════════════════════════════════════════════════

class Question(BaseModel):
    """
    A single exam question extracted from a question paper PDF.

    This is the core output of Member 3's exam parser.

    Fields marked 'Member 3' are populated by parser.py.
    Fields marked 'Member 4' are left NULL by parser.py.
    Member 4 fills them after NLP processing.

    Usage:
        q = Question(
            question_id="q-001",
            document_id=101,
            page=1,
            raw_text="Q1. Explain normalization in DBMS.",
            year=2025,
            exam_type="End Semester",
            section="A",
            marks=5,
            is_compulsory=True,
        )
        print(q.model_dump_json(indent=2))
    """

    # ── Identity fields ────────────────────────────────────────────────────
    question_id: str = Field(
        description="Unique identifier for this question. "
                    "Generated by Member 3 as a UUID string. "
                    "Becomes an INTEGER PRIMARY KEY in the DB (Member 6 handles that)."
    )

    document_id: int = Field(
        description="The ID of the source document (PDF). "
                    "Provided by Member 6's ingestion system. "
                    "All questions from the same PDF share this ID."
    )

    # ── Location fields ────────────────────────────────────────────────────
    page: int = Field(
        ge=1,   # must be >= 1  (1-indexed, never 0)
        description="The PDF page number this question was found on. 1-indexed."
    )

    # ── Text fields ────────────────────────────────────────────────────────
    raw_text: str = Field(
        description="The question text exactly as extracted from the PDF "
                    "or OCR. Not corrected or rewritten. "
                    "Member 4 uses this as input for NLP cleaning."
    )

    cleaned_text: Optional[str] = Field(
        default=None,
        description="[Member 4 fills this] "
                    "Semantically cleaned version of raw_text. "
                    "NULL when Member 3 creates the record."
    )

    # ── Document-level metadata ────────────────────────────────────────────
    year: Optional[int] = Field(
        default=None,
        description="The exam year, extracted from the document header and "
                    "propagated to all questions. "
                    "NULL if the year cannot be reliably determined."
    )

    exam_type: Optional[str] = Field(
        default=None,
        description="Type of exam: 'End Semester', 'Mid Semester', "
                    "'Internal', 'Supplementary', 'Unit Test', 'Quiz', etc. "
                    "NULL if not determinable."
    )

    # ── Question-level metadata ────────────────────────────────────────────
    section: Optional[str] = Field(
        default=None,
        description="The section of the paper this question belongs to. "
                    "E.g. 'A', 'B', 'I', 'II'. "
                    "NULL if the paper has no section structure."
    )

    marks: Optional[int] = Field(
        default=None,
        ge=1,       # if set, must be at least 1
        le=100,     # if set, must be at most 100
        description="Marks allocated to this question. "
                    "Extracted from '[5 marks]', '(10 Marks)', etc. "
                    "NULL if marks cannot be confidently determined."
    )

    is_compulsory: Optional[bool] = Field(
        default=None,
        description="Whether this question is compulsory. "
                    "True  = must be answered. "
                    "False = optional (e.g. 'answer any 3'). "
                    "None  = could not be determined."
    )

    # ── Fields filled by Member 4 (NULL at creation) ──────────────────────
    topic_id: Optional[int] = Field(
        default=None,
        description="[Member 4 fills this] "
                    "Foreign key to the Topic table. "
                    "NULL until Member 4 runs NLP topic classification."
    )

    repeat_group_id: Optional[int] = Field(
        default=None,
        description="[Member 4 fills this] "
                    "ID of the repeat group if this question appeared "
                    "in multiple papers. "
                    "NULL until Member 4 runs repeat detection."
    )

    # ── Validators ─────────────────────────────────────────────────────────

    @field_validator("raw_text")
    @classmethod
    def raw_text_must_not_be_empty(cls, v: str) -> str:
        """
        raw_text must not be an empty string.
        A Question with no text is meaningless.
        """
        if not v or not v.strip():
            raise ValueError("raw_text cannot be empty")
        return v

    @field_validator("year")
    @classmethod
    def year_must_be_valid(cls, v: Optional[int]) -> Optional[int]:
        """
        If year is provided, it must be in the valid range 1990-2099.
        We never store an obviously wrong year.
        """
        if v is not None and not (1990 <= v <= 2099):
            raise ValueError(f"year {v} is outside valid range 1990-2099")
        return v

    @field_validator("question_id")
    @classmethod
    def question_id_must_not_be_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("question_id cannot be empty")
        return v

    # ── Pydantic config ────────────────────────────────────────────────────
    model_config = {
        # Allow extra fields to be ignored (future-proofing)
        # so Member 6 can add fields without breaking our model
        "extra": "ignore",

        # Validate default values too
        "validate_default": True,

        # JSON schema title
        "json_schema_extra": {
            "example": {
                "question_id": "q-550e8400-e29b-41d4-a716-446655440000",
                "document_id": 101,
                "page": 1,
                "raw_text": "Q1. Explain normalization in DBMS.",
                "cleaned_text": None,
                "year": 2025,
                "exam_type": "End Semester",
                "section": "A",
                "marks": 5,
                "is_compulsory": True,
                "topic_id": None,
                "repeat_group_id": None,
            }
        }
    }


# ═══════════════════════════════════════════════════════════════════
# PARSED DOCUMENT MODEL
# ═══════════════════════════════════════════════════════════════════

class ParsedDocument(BaseModel):
    """
    The full result of parsing one exam paper PDF.

    This is what parser.py returns and what the API endpoint sends back.

    Contains:
        - Document-level metadata (year, exam_type)
        - A list of all Question records extracted from the paper
    """

    document_id: int = Field(
        description="The document ID provided by Member 6's ingestion system."
    )

    doc_type: str = Field(
        default="question_paper",
        description="Type of document. Always 'question_paper' for Member 3's output."
    )

    year: Optional[int] = Field(
        default=None,
        description="Year extracted from the document header."
    )

    exam_type: Optional[str] = Field(
        default=None,
        description="Exam type extracted from the document header."
    )

    total_pages: int = Field(
        default=0,
        description="Total number of pages in the PDF."
    )

    questions: list[Question] = Field(
        default_factory=list,
        description="All questions extracted from this document."
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "document_id": 101,
                "doc_type": "question_paper",
                "year": 2025,
                "exam_type": "End Semester",
                "total_pages": 3,
                "questions": [
                    {
                        "question_id": "q-001",
                        "document_id": 101,
                        "page": 1,
                        "raw_text": "Q1. Explain normalization in DBMS.",
                        "cleaned_text": None,
                        "year": 2025,
                        "exam_type": "End Semester",
                        "section": "A",
                        "marks": 5,
                        "is_compulsory": True,
                        "topic_id": None,
                        "repeat_group_id": None,
                    }
                ]
            }
        }
    }


# ═══════════════════════════════════════════════════════════════════
# TOPIC MODEL
# ═══════════════════════════════════════════════════════════════════

class Topic(BaseModel):
    """
    A topic from the official syllabus.

    Loaded into the DB by syllabus/loader.py.
    Assigned to questions by Member 4 (topic_id field).

    The topic_id is an integer (DB auto-increment primary key).
    topic_code is a human-readable identifier like "DBMS-01".
    """

    topic_id: Optional[int] = Field(
        default=None,
        description="Database primary key. Auto-assigned on insert. "
                    "None before DB insertion."
    )

    topic_code: str = Field(
        description="Human-readable unique code. E.g. 'DBMS-01', 'DBMS-02'. "
                    "Used for referencing topics in spreadsheets or reports."
    )

    name: str = Field(
        description="Full topic name. E.g. 'Normalization', 'ER Model'."
    )

    syllabus_unit: str = Field(
        description="The unit in the official syllabus. E.g. 'Unit 1', 'Unit 2'."
    )

    @field_validator("topic_code", "name", "syllabus_unit")
    @classmethod
    def must_not_be_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()

    model_config = {
        "json_schema_extra": {
            "example": {
                "topic_id": 2,
                "topic_code": "DBMS-02",
                "name": "Normalization",
                "syllabus_unit": "Unit 2"
            }
        }
    }


# ═══════════════════════════════════════════════════════════════════
# HELPER: build a Question from parser output
# ═══════════════════════════════════════════════════════════════════

def make_question(
    document_id: int,
    page: int,
    raw_text: str,
    year: Optional[int] = None,
    exam_type: Optional[str] = None,
    section: Optional[str] = None,
    marks: Optional[int] = None,
    is_compulsory: Optional[bool] = None,
) -> Question:
    """
    Convenience factory to build a Question with a generated UUID.

    Use this in parser.py instead of constructing Question() directly.
    It handles question_id generation automatically.

    Parameters match the Question fields. All optional fields default None.

    Example:
        q = make_question(
            document_id=101,
            page=1,
            raw_text="Q1. Explain normalization. [5 marks]",
            year=2025,
            exam_type="End Semester",
            section="A",
            marks=5,
            is_compulsory=True,
        )
    """
    return Question(
        question_id=f"q-{uuid.uuid4()}",
        document_id=document_id,
        page=page,
        raw_text=raw_text,
        cleaned_text=None,       # Member 4 fills this
        year=year,
        exam_type=exam_type,
        section=section,
        marks=marks,
        is_compulsory=is_compulsory,
        topic_id=None,           # Member 4 fills this
        repeat_group_id=None,    # Member 4 fills this
    )
